[package]
name = "gitlab"
version = "0.1.0"
authors = ["Fred Hsu <fredlhsu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.125", features = ["derive"] }
